# Markdownlint configuration
# See https://github.com/DavidAnson/markdownlint

default: true

# MD013 - Line length
MD013:
  line_length: 120
  tables: false
  code_blocks: false

# MD033 - Allow inline HTML
MD033: false

# MD041 - First line in file should be a top level header
MD041: false
